### ISSUE TITLE
data_processing folder is missing

### ISSUE THREAD

**Issue by kjaugustin** [mhoogen/MIMIC2V3_code#1]
from data_processing.process_data import createProcessedFiles
this import fails. data_processing folder is missing

**Comment by alielhassouni** [comment]
Hi kjaugustin,

Thanks for the comment!

The folder data_processing is indeed missing. I've attached the missing folder. The repo needs to be updated as well.

[data_processing.zip](https://github.com/mhoogen/MIMIC2V3_code/files/724468/data_processing.zip)

**Comment by alielhassouni** [comment]
Repo has been updated as well.

**Comment by kjaugustin** [comment]
Thank you!
